### ISSUE TITLE
List only API products purchased by a team

### ISSUE THREAD

**Issue by raakesh-blokhra** [apigee/apigee-m10n-drupal#336]
**Is your feature request related to a problem? Please describe.**
Customer noticed some feature not implemented yet in Drupal Module, regarding teams in monetization:

In a team project you can see API products (rate plans) which are not purchased by the team.

**Describe the solution you'd like**
The customer would like to see only the purchased rate plan in the project.

**Comment by antoniocasella** [comment]
Hi, just a clarification, we are currently using Apigee Edge.
I noticed a different behavior between personal project and teams project sections.
In personal project section developers can add into their projects only API they bought. Instead in team projects section all API are visible, so a team developer can create a project by adding API that can't be used.
I don't know if it is bug or a intentional behaviour

**Comment by divya-intelli** [comment]
Hi @antoniocasella, if possible please attach a screenshot or screen recording without any personal information like emails, etc.

**Comment by kedarkhaire** [comment]
Hi @antoniocasella,
We are able to replicate the issue.
We will get back to you once the PR is ready.
Thanks!
