### ISSUE TITLE
INTERNAL: Cost received is non positive 

### ISSUE THREAD

**Issue by cen1** [apigee/apigee-m10n-drupal#402]
## Description
When setting 0$ setup fee for the rate plan through API, the purchase through Drupal Portal fails with `INTERNAL: Cost received is non positive `

Example of rate plan:
```
{
  "name": "...",
  "apiproduct": "Test",
  "displayName": "Test",
  "billingPeriod": "MONTHLY",
  "currencyCode": "USD",
  "description": "test",
  "setupFee": {
    "currencyCode": "USD"
  },
  "state": "PUBLISHED",
  "startTime": "1661524015832"
}
```

## Steps to Reproduce
1. Create plan as described above
2. Purchase the plan through the API portal

## Actual Behavior
Error

## Expected Behavior
Plan is free so it should succeed

**Comment by divya-intelli** [comment]
Hi @cen1 ,
Is the error coming for  ApigeeX or 4g?
Please provide the Drupal error log also the output`composer show` .

**Comment by cen1** [comment]
There is no error log in drupal. It seems some kind of range check either inside m10n or perhaps commerce?

```
drupal/core                                    9.4.8        Drupal is an open source content management platform powering millions of websites and applications.
apigee/apigee-client-php                       2.0.16       Client library for connecting to the Apigee Edge API.
apigee/apigee-mock-client-php                  1.1.1        To be used for queueing mock API responses for the `apigee/apigee-client-php` library.
apigee/apigee_devportal_kickstart              2.1.0        A fast demo and starting point for Apigee Developer Portals.
drupal/apigee_api_catalog                      3.0.2        Apigee API Catalog for Drupal
drupal/apigee_edge                             2.0.5        Apigee Edge for Drupal.
drupal/apigee_m10n                             2.0.3        Apigee Edge Monetization for Drupal
```
<img width="365" alt="Screenshot 2022-10-26 at 14 57 28" src="https://user-images.githubusercontent.com/1158861/198031904-2e58a86a-86d0-429c-bd76-885fbf4616e0.png">

**Comment by HiddenFennec** [comment]
I was also getting this error. This is occurring because you may have checked the "Charge initialization fee" and set the value to zero like so:

<img width="353" alt="image" src="https://github.com/apigee/apigee-m10n-drupal/assets/36107609/d4d892cf-19c6-4805-a73d-5cc877ed75d0">

The way I fixed the error, was by simply unchecking the "Charge initialization fee". I think this is a validation bug on the UI which leads to this drupal error. That being said, I think it should be fixed on the Drupal side, as you can possibly can also replicate the error (untested) via the API (https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.apiproducts.rateplans#RatePlan), by attaching an "Money" object in the setupFee, and setting the value in the object to 0 - therefore a UI fix in Apigee won't be enough.

**Comment by divya-intelli** [comment]
Thank you @HiddenFennec for identifying what is causing the issue. 
@cen1 please try unchecking the "Charge initialization fee" as mentioned by @HiddenFennec to see if it fixes the issue for you.
@HiddenFennec if you have a fix for this issue, feel free to create a PR.

**Comment by divya-intelli** [comment]
@HiddenFennec @cen1 , we are able to replicate this issue and get back with a fix.

**Comment by divya-intelli** [comment]
@HiddenFennec , @cen1 

When we set the `Charge initialization fee` as `0` and try to buy the rateplan, `INTERNAL: Cost received is non positive ` error is thrown.  
Unchecking `Charge initialization fee`, resolves the error.
In Drupal we use the subscription API to buy a rateplan. An exception is thrown by Apigee if `Charge initialization fee` is set as `0`.

![Screenshot 2023-08-30 at 2 20 45 PM](https://github.com/apigee/apigee-m10n-drupal/assets/75604843/6f4edf33-cd14-4eb3-81d6-145521c51e52)



 Please create a support ticket in Apigee for this.

 Closing this issue as the error is from Apigee.
